# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/commit-message-generator/text
Content-Type: application/json
Accept: application/json

{
  "secret_key": "XXXX",
  "model_url": "XXXX",
  "api_key": "XXXX",
  "message": "this is a test messagexzcxzcdacsdcsfvczvcv"
}


